# Generated by Django 4.1.5 on 2023-03-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='re_password',
        ),
    ]
