# Generated by Django 4.1.5 on 2023-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0003_remove_signup_re_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('registration', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='pdfs/')),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('confirm_password', models.CharField(max_length=25)),
            ],
        ),
    ]
