# Generated by Django 4.1.5 on 2023-03-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0004_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
