# Generated by Django 4.1.5 on 2023-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0007_remove_registration_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=6)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
