# Generated by Django 4.1.5 on 2023-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0008_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_model',
            name='amount',
            field=models.IntegerField(max_length=10),
        ),
    ]
