# Generated by Django 4.1.5 on 2023-03-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0014_remove_registration_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='document',
            field=models.FileField(default=11, upload_to='pdfs/'),
            preserve_default=False,
        ),
    ]
