# Generated by Django 4.1.5 on 2023-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0017_uplaod_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplaod_file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='pdfs/'),
        ),
    ]
