# Generated by Django 4.1.5 on 2023-03-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0028_alter_registration_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='patient_images')),
                ('amount', models.IntegerField(max_length=6)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
