# Generated by Django 4.1.5 on 2023-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0029_patient_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
