# Generated by Django 4.1.5 on 2023-03-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0029_patient_model_alter_registration_registration_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
