# Generated by Django 4.1.5 on 2023-04-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_lives_app1', '0030_alter_patient_model_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=125, unique=True),
        ),
    ]
